---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
one set is original data set and one more is data set without NA values
```{r}
actdt = read.csv("activity.csv")
#head(actdt)
actvlt = !is.na(actdt[,1])
actvldt = actdt[actvlt,][]
#head(actvldt)
actdt$date = as.Date(actdt$date,"%Y-%m-%d")
str(actdt)
```




## What is mean total number of steps taken per day?
let total number of steps taken per day be totstp
```{r}
library(dplyr)
library(ggplot2)
totalstp = actdt %>% group_by(date) %>% summarize(meanstp = mean(steps,na.rm = TRUE),totstp = sum(steps,na.rm = TRUE),medstp = median(steps,na.rm = TRUE))
head(totalstp)
hist(totalstp$totstp)
median(totalstp$medstp,na.rm = TRUE)
mean(totalstp$meanstp,na.rm = TRUE)
```




## What is the average daily activity pattern?
```{r}
actbyint = actdt %>% group_by(interval) %>% summarize(avgstp = mean(steps,na.rm = TRUE))
head(actbyint)
plot(actbyint$interval,actbyint$avgstp,type = "l")
actbyint[which.max(actbyint$avgstp),]
```



## Imputing missing values

```{r}
missval = is.na(actdt[,1])
indexvect = actdt[missval,3]
sum(missval)
for (i in 1:nrow(actdt)) {
  for(k in 0:471){
  if((is.na(actdt[i,1]) == TRUE) & (actdt[i,3] == 5*k) ){
    actdt[i,1] = actbyint[actbyint[,1] == 5*k,][,2]
  }
  }
}
actnewdt = actdt
totalstpn = actnewdt %>% group_by(date) %>% summarize(meanstp = mean(steps,na.rm = TRUE),totstp = sum(steps,na.rm = TRUE),medstp = median(steps,na.rm = TRUE))
head(totalstpn)
hist(totalstpn$totstp)
median(totalstpn$medstp,na.rm = TRUE)
mean(totalstpn$meanstp,na.rm = TRUE)

```


## Are there differences in activity patterns between weekdays and weekends?
```{r}

actdtwk = actdt
actdtwk$day = weekdays(actdtwk$date)
weekenddtlg = filter(actdtwk,day == c("Saturday","Sunday"))
head(weekenddtlg)
weekdtlg = filter(actdtwk,day == c("Monday","Tuesday","Wednesday","Thursday","Friday"))
head(weekdtlg)
actbyintwk = weekdtlg %>% group_by(interval) %>% summarize(avgstp = mean(steps,na.rm = TRUE))
head(actbyintwk)
plot(actbyintwk$interval,actbyintwk$avgstp,type = "l")
actbyintwnd = weekenddtlg %>% group_by(interval) %>% summarize(avgstp = mean(steps,na.rm = TRUE))
head(actbyintwnd)
plot(actbyintwnd$interval,actbyintwnd$avgstp,type = "l")
```

